/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultadoRouteImport } from './routes/resultado'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultadoPublicTokenRouteImport } from './routes/resultado.$publicToken'

const ResultadoRoute = ResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadoPublicTokenRoute = ResultadoPublicTokenRouteImport.update({
  id: '/$publicToken',
  path: '/$publicToken',
  getParentRoute: () => ResultadoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resultado': typeof ResultadoRouteWithChildren
  '/resultado/$publicToken': typeof ResultadoPublicTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resultado': typeof ResultadoRouteWithChildren
  '/resultado/$publicToken': typeof ResultadoPublicTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resultado': typeof ResultadoRouteWithChildren
  '/resultado/$publicToken': typeof ResultadoPublicTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/resultado' | '/resultado/$publicToken'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/resultado' | '/resultado/$publicToken'
  id: '__root__' | '/' | '/resultado' | '/resultado/$publicToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResultadoRoute: typeof ResultadoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultado': {
      id: '/resultado'
      path: '/resultado'
      fullPath: '/resultado'
      preLoaderRoute: typeof ResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultado/$publicToken': {
      id: '/resultado/$publicToken'
      path: '/$publicToken'
      fullPath: '/resultado/$publicToken'
      preLoaderRoute: typeof ResultadoPublicTokenRouteImport
      parentRoute: typeof ResultadoRoute
    }
  }
}

interface ResultadoRouteChildren {
  ResultadoPublicTokenRoute: typeof ResultadoPublicTokenRoute
}

const ResultadoRouteChildren: ResultadoRouteChildren = {
  ResultadoPublicTokenRoute: ResultadoPublicTokenRoute,
}

const ResultadoRouteWithChildren = ResultadoRoute._addFileChildren(
  ResultadoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResultadoRoute: ResultadoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
