/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultadoRouteImport } from './routes/resultado'
import { Route as FilaDeImpressaoRouteImport } from './routes/fila-de-impressao'
import { Route as DadosRouteImport } from './routes/dados'
import { Route as ConfigurarCapitalRouteImport } from './routes/configurar-capital'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultadoPublicTokenRouteImport } from './routes/resultado.$publicToken'
import { Route as ImprimirQueueIdRouteImport } from './routes/imprimir.$queueId'
import { Route as ExperienciaCapitalSlugRouteImport } from './routes/experiencia.$capitalSlug'

const ResultadoRoute = ResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const FilaDeImpressaoRoute = FilaDeImpressaoRouteImport.update({
  id: '/fila-de-impressao',
  path: '/fila-de-impressao',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosRoute = DadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurarCapitalRoute = ConfigurarCapitalRouteImport.update({
  id: '/configurar-capital',
  path: '/configurar-capital',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadoPublicTokenRoute = ResultadoPublicTokenRouteImport.update({
  id: '/$publicToken',
  path: '/$publicToken',
  getParentRoute: () => ResultadoRoute,
} as any)
const ImprimirQueueIdRoute = ImprimirQueueIdRouteImport.update({
  id: '/imprimir/$queueId',
  path: '/imprimir/$queueId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciaCapitalSlugRoute = ExperienciaCapitalSlugRouteImport.update({
  id: '/experiencia/$capitalSlug',
  path: '/experiencia/$capitalSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configurar-capital': typeof ConfigurarCapitalRoute
  '/dados': typeof DadosRoute
  '/fila-de-impressao': typeof FilaDeImpressaoRoute
  '/resultado': typeof ResultadoRouteWithChildren
  '/experiencia/$capitalSlug': typeof ExperienciaCapitalSlugRoute
  '/imprimir/$queueId': typeof ImprimirQueueIdRoute
  '/resultado/$publicToken': typeof ResultadoPublicTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configurar-capital': typeof ConfigurarCapitalRoute
  '/dados': typeof DadosRoute
  '/fila-de-impressao': typeof FilaDeImpressaoRoute
  '/resultado': typeof ResultadoRouteWithChildren
  '/experiencia/$capitalSlug': typeof ExperienciaCapitalSlugRoute
  '/imprimir/$queueId': typeof ImprimirQueueIdRoute
  '/resultado/$publicToken': typeof ResultadoPublicTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configurar-capital': typeof ConfigurarCapitalRoute
  '/dados': typeof DadosRoute
  '/fila-de-impressao': typeof FilaDeImpressaoRoute
  '/resultado': typeof ResultadoRouteWithChildren
  '/experiencia/$capitalSlug': typeof ExperienciaCapitalSlugRoute
  '/imprimir/$queueId': typeof ImprimirQueueIdRoute
  '/resultado/$publicToken': typeof ResultadoPublicTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configurar-capital'
    | '/dados'
    | '/fila-de-impressao'
    | '/resultado'
    | '/experiencia/$capitalSlug'
    | '/imprimir/$queueId'
    | '/resultado/$publicToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configurar-capital'
    | '/dados'
    | '/fila-de-impressao'
    | '/resultado'
    | '/experiencia/$capitalSlug'
    | '/imprimir/$queueId'
    | '/resultado/$publicToken'
  id:
    | '__root__'
    | '/'
    | '/configurar-capital'
    | '/dados'
    | '/fila-de-impressao'
    | '/resultado'
    | '/experiencia/$capitalSlug'
    | '/imprimir/$queueId'
    | '/resultado/$publicToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigurarCapitalRoute: typeof ConfigurarCapitalRoute
  DadosRoute: typeof DadosRoute
  FilaDeImpressaoRoute: typeof FilaDeImpressaoRoute
  ResultadoRoute: typeof ResultadoRouteWithChildren
  ExperienciaCapitalSlugRoute: typeof ExperienciaCapitalSlugRoute
  ImprimirQueueIdRoute: typeof ImprimirQueueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultado': {
      id: '/resultado'
      path: '/resultado'
      fullPath: '/resultado'
      preLoaderRoute: typeof ResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fila-de-impressao': {
      id: '/fila-de-impressao'
      path: '/fila-de-impressao'
      fullPath: '/fila-de-impressao'
      preLoaderRoute: typeof FilaDeImpressaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados': {
      id: '/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof DadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurar-capital': {
      id: '/configurar-capital'
      path: '/configurar-capital'
      fullPath: '/configurar-capital'
      preLoaderRoute: typeof ConfigurarCapitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultado/$publicToken': {
      id: '/resultado/$publicToken'
      path: '/$publicToken'
      fullPath: '/resultado/$publicToken'
      preLoaderRoute: typeof ResultadoPublicTokenRouteImport
      parentRoute: typeof ResultadoRoute
    }
    '/imprimir/$queueId': {
      id: '/imprimir/$queueId'
      path: '/imprimir/$queueId'
      fullPath: '/imprimir/$queueId'
      preLoaderRoute: typeof ImprimirQueueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencia/$capitalSlug': {
      id: '/experiencia/$capitalSlug'
      path: '/experiencia/$capitalSlug'
      fullPath: '/experiencia/$capitalSlug'
      preLoaderRoute: typeof ExperienciaCapitalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResultadoRouteChildren {
  ResultadoPublicTokenRoute: typeof ResultadoPublicTokenRoute
}

const ResultadoRouteChildren: ResultadoRouteChildren = {
  ResultadoPublicTokenRoute: ResultadoPublicTokenRoute,
}

const ResultadoRouteWithChildren = ResultadoRoute._addFileChildren(
  ResultadoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigurarCapitalRoute: ConfigurarCapitalRoute,
  DadosRoute: DadosRoute,
  FilaDeImpressaoRoute: FilaDeImpressaoRoute,
  ResultadoRoute: ResultadoRouteWithChildren,
  ExperienciaCapitalSlugRoute: ExperienciaCapitalSlugRoute,
  ImprimirQueueIdRoute: ImprimirQueueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
